/* 7TH UNIVERSE ESPORTS — V6
   GVG-style blue esports frontend.

   IMPORTANT:
   - Supabase publishable key only. Never put a secret/service_role key here.
   - Registration is created by the auth.users database trigger.
   - Login requires: approved profile + approved team membership + active team.
   - Results are permanent: WIN +3 / LOSS -3, no weekly reset.
   - Ranking is all-time and only approved results count.
   - WhatsApp delivery is server-side: Supabase DB webhook -> Railway/Baileys.
*/
(() => {
  "use strict";

  const SUPABASE_URL = "https://otrjuqcutwlwvzyruhaq.supabase.co";
  const SUPABASE_PUBLISHABLE_KEY = "sb_publishable_ro_4z-4OdgFCda9pT8Z3Pg_UEnY4aTE";
  const LOGO_BUCKET = "team-logos";
  const RESULT_BUCKET = "result-proofs";
  const MAX_IMAGE_MB = 3;

  const supabase = window.supabase.createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
    auth: { persistSession:true, autoRefreshToken:true, detectSessionInUrl:true }
  });

  const app=document.getElementById("app");
  const modal=document.getElementById("modalBackdrop");
  const modalTitle=document.getElementById("modalTitle");
  const modalBody=document.getElementById("modalBody");
  const modalClose=document.getElementById("modalClose");
  const toast=document.getElementById("toast");

  const state={user:null,profile:null,membership:null,team:null,isAdmin:false,screen:"login",section:"dashboard",adminSection:"registrations",challenges:[],recruitment:[],results:[],rankings:[],registrations:[],teams:[]};

  const esc=v=>String(v??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#039;"}[m]));
  const cleanPhone=value=>{let v=String(value||"").trim().replace(/[^\d+]/g,"");if(v.startsWith("00"))v="+"+v.slice(2);if(v.startsWith("03"))v="+92"+v.slice(1);if(v.startsWith("92"))v="+"+v;return v;};
  const fmtDate=v=>{if(!v)return"—";const d=new Date(v);return Number.isNaN(d.getTime())?"—":d.toLocaleString("en-PK",{dateStyle:"medium",timeStyle:"short"});};
  const roleName=r=>({admin:"Administrator",leader:"Team Leader / IGL",sub_leader:"Sub-Leader",member:"Member"}[r]||r||"Member");
  const logo=(url,label="7U",cls="mini-logo")=>url?`<img class="${cls}" src="${esc(url)}" alt="${esc(label)} logo">`:`<div class="${cls} mini-placeholder">${esc(String(label).slice(0,3).toUpperCase())}</div>`;

  function showToast(message,type="ok"){toast.textContent=message;toast.className=`show ${type}`;clearTimeout(showToast.t);showToast.t=setTimeout(()=>toast.className="",4500);}
  function showModal(title,body){modalTitle.textContent=title;modalBody.innerHTML=body;modal.classList.add("open");modal.setAttribute("aria-hidden","false");}
  function closeModal(){modal.classList.remove("open");modal.setAttribute("aria-hidden","true");}
  modalClose?.addEventListener("click",closeModal);modal?.addEventListener("click",e=>{if(e.target===modal)closeModal();});

  async function getProfile(uid){const {data,error}=await supabase.from("profiles").select("*").eq("id",uid).maybeSingle();if(error)throw error;return data;}
  async function getMembership(uid){const {data,error}=await supabase.from("team_members").select("id,team_id,user_id,role,status,teams(id,name,logo_url,igl_name,status,created_at)").eq("user_id",uid).order("created_at",{ascending:false}).limit(1).maybeSingle();if(error)throw error;return data||null;}
  async function repairMembership(){
    if(!state.user||!state.profile||state.profile.role==="admin")return await getMembership(state.user?.id);
    const existing=await getMembership(state.user.id);if(existing)return existing;
    const {error}=await supabase.rpc("repair_my_team_membership");if(error)throw error;
    return await getMembership(state.user.id);
  }

  async function hydrateSession(){
    const {data:{session}}=await supabase.auth.getSession();state.user=session?.user||null;
    if(!state.user){state.profile=null;state.membership=null;state.team=null;state.isAdmin=false;state.screen=new URLSearchParams(location.search).get("register")==="1"?"register":"login";render();return;}
    try{
      state.profile=await getProfile(state.user.id);
      if(!state.profile){await supabase.auth.signOut();state.screen="login";render();showToast("Registration record not found. Please contact the admin.","error");return;}
      state.isAdmin=state.profile.role==="admin"&&state.profile.status==="approved";
      if(!state.isAdmin && state.profile.status!=="approved"){
        const s=state.profile.status;await supabase.auth.signOut();state.screen="login";render();showToast(s==="banned"?"Your account is banned.":"Your registration is pending administrator approval.","error");return;
      }
      state.membership=await repairMembership();state.team=state.membership?.teams||null;
      if(!state.isAdmin && (!state.membership||state.membership.status!=="approved"||state.team?.status!=="active")){
        await supabase.auth.signOut();state.screen="login";render();showToast("Your team is not confirmed yet. Please wait for admin approval.","error");return;
      }
      state.screen="member";state.section="dashboard";render();
    }catch(error){console.error(error);await supabase.auth.signOut();state.screen="login";render();showToast(error.message||"Could not load account.","error");}
  }
  supabase.auth.onAuthStateChange(async event=>{if(["SIGNED_IN","SIGNED_OUT","TOKEN_REFRESHED"].includes(event))await hydrateSession();});

  /* ---------------- AUTH UI ---------------- */
  function authHeader(register=false){return `<div class="public-header"><div class="public-nav"><div class="nav-left"><button class="nav-action" id="publicAdminBtn">ADMIN ACCESS</button></div><div class="brand-center"><img class="brand-logo" src="./7th-universe-esports-logo.png" alt="7TH UNIVERSE ESPORTS"><div><div class="brand-title">7TH <span>UNIVERSE</span></div><div class="brand-sub">FREE FIRE • ESPORTS PLATFORM</div></div></div><div class="nav-right">${register?`<button class="nav-action" id="publicLoginBtn">BACK TO LOGIN</button>`:`<button class="nav-action register" id="publicRegisterBtn">REGISTER NEW ACCOUNT</button>`}</div></div></div>`;}
  function renderAuth(){const reg=state.screen==="register";app.innerHTML=`${authHeader(reg)}<main class="public-page"><div class="auth-layout"><section class="card auth-hero"><div class="kicker">FREE FIRE ESPORTS PLATFORM</div><h1><span class="w">7TH</span> <span class="b">UNIVERSE</span> <span class="c">ESPORTS</span></h1><h2>Practice. Recruit. Compete.</h2><div class="desc">A dedicated Free Fire esports workspace for approved teams and members. Build Clash Squad practice connections, publish recruitment requirements, submit match results and climb the permanent all-time ranking.</div><div class="feature-grid"><div class="feature"><b>CLASH SQUAD PRACTICE</b><span>Open challenges are automatically for EVERYONE.</span></div><div class="feature"><b>TEAM / PLAYER RECRUITMENT</b><span>Find roles, players and serious competitive opportunities.</span></div><div class="feature"><b>PERMANENT RANKING</b><span>Approved wins add +3 and losses subtract −3. Never reset.</span></div><div class="feature"><b>2 MEMBERS / TEAM</b><span>Leader/IGL + Sub-Leader. Database enforced.</span></div></div><div class="access-note"><b>SECURE MEMBER AREA:</b> Practice, Results, Rankings, Recruitment, Team Profile and Administration are available after authentication.</div></section><section class="card auth-card"><div class="auth-inner"><div class="auth-logo-row"><img src="./7th-universe-esports-logo.png" alt="7U"><div><strong>${reg?"CREATE ACCOUNT":"MEMBER LOGIN"}</strong><span>7TH UNIVERSE ESPORTS</span></div></div><div class="auth-tabs"><button class="auth-tab ${!reg?"active":""}" id="loginTab">LOGIN</button><button class="auth-tab ${reg?"active":""}" id="registerTab">REGISTER</button></div>${reg?registrationForm():loginForm()}</div></section></div></main>`;bindAuth();}
  function bindAuth(){document.getElementById("publicAdminBtn")?.addEventListener("click",()=>{state.screen="admin-login";render();});document.getElementById("publicRegisterBtn")?.addEventListener("click",goRegister);document.getElementById("publicLoginBtn")?.addEventListener("click",goLogin);document.getElementById("loginTab")?.addEventListener("click",goLogin);document.getElementById("registerTab")?.addEventListener("click",goRegister);document.getElementById("microRegister")?.addEventListener("click",goRegister);document.getElementById("loginForm")?.addEventListener("submit",handleLogin);document.getElementById("registerForm")?.addEventListener("submit",handleRegister);}
  function loginForm(){return `<div class="auth-title"><div class="kicker">AUTHORIZED MEMBERS</div><h1 class="title">LOGIN</h1><p>Use your registered email or mobile number and password.</p></div><form id="loginForm" style="margin-top:16px"><div class="field-grid"><label class="full">EMAIL / MOBILE NUMBER<input id="loginIdentifier" autocomplete="username" placeholder="leader@example.com or 03XXXXXXXXX" required></label><label class="full">PASSWORD<input id="loginPassword" type="password" autocomplete="current-password" placeholder="Your password" required></label></div><div class="auth-actions"><button class="btn btn-primary" type="submit">LOGIN TO ESPORTS</button></div><div class="micro">New member? <button type="button" id="microRegister">Register New Account</button></div><div class="status info show" style="margin-top:12px">Your team must be approved before Practice, Results, Rankings and Recruitment become active.</div></form>`;}
  function registrationForm(){return `<div class="auth-title"><div class="kicker">CONTROLLED REGISTRATION</div><h1 class="title">REGISTER</h1><p>Create one of the two permitted website roles for your team.</p></div><form id="registerForm" style="margin-top:16px"><div class="field-grid"><label>TEAM NAME *<input id="regTeamName" maxlength="50" placeholder="Your esports team" required></label><label>MEMBER ROLE *<select id="regRole"><option value="leader">Team Leader / IGL</option><option value="sub_leader">Sub-Leader</option></select></label><label>LEADER / MEMBER NAME *<input id="regName" maxlength="60" required placeholder="Name"></label><label>CONTACT NUMBER *<input id="regPhone" maxlength="20" required placeholder="03XXXXXXXXX"></label><label class="full">EMAIL *<input id="regEmail" type="email" maxlength="120" required placeholder="leader@example.com"></label><label>PASSWORD *<input id="regPassword" type="password" minlength="8" required placeholder="Minimum 8 characters"></label><label>CONFIRM PASSWORD *<input id="regPassword2" type="password" minlength="8" required placeholder="Repeat password"></label><label class="full">TEAM LOGO — OPTIONAL<input id="regLogo" type="file" accept="image/png,image/jpeg,image/webp"></label></div><div class="hint">Logo can be uploaded/changed later from TEAM PROFILE. PNG/JPG/WEBP • Maximum ${MAX_IMAGE_MB} MB.</div><div class="access-note" style="margin-top:13px"><b>APPROVAL:</b> Register → Pending → Admin Review → Approved → Login.</div><div class="auth-actions"><button class="btn btn-primary" type="submit">SUBMIT REGISTRATION</button></div></form>`;}
  function goLogin(){const u=new URL(location.href);u.searchParams.delete("register");history.replaceState({},"",u);state.screen="login";render();}
  function goRegister(){const u=new URL(location.href);u.searchParams.set("register","1");history.replaceState({},"",u);state.screen="register";render();}

  async function handleLogin(e){e.preventDefault();try{const id=document.getElementById("loginIdentifier").value.trim(),pw=document.getElementById("loginPassword").value;const creds=id.includes("@")?{email:id.toLowerCase(),password:pw}:{phone:cleanPhone(id),password:pw};const {error}=await supabase.auth.signInWithPassword(creds);if(error)throw error;}catch(error){console.error(error);showToast(error.message||"Login failed.","error");}}
  async function handleRegister(e){e.preventDefault();try{const teamName=document.getElementById("regTeamName").value.trim(),role=document.getElementById("regRole").value,name=document.getElementById("regName").value.trim(),phone=cleanPhone(document.getElementById("regPhone").value),email=document.getElementById("regEmail").value.trim().toLowerCase(),pw=document.getElementById("regPassword").value,pw2=document.getElementById("regPassword2").value;const file=document.getElementById("regLogo").files?.[0]||null;if(!teamName||!name||!email||!phone)throw new Error("Complete all required fields.");if(!/^\+92\d{10}$/.test(phone))throw new Error("Enter a valid Pakistan mobile number.");if(pw.length<8)throw new Error("Password must be at least 8 characters.");if(pw!==pw2)throw new Error("Passwords do not match.");if(file&&(file.size>MAX_IMAGE_MB*1024*1024||!/^image\/(png|jpeg|webp)$/.test(file.type)))throw new Error(`Logo must be PNG/JPG/WEBP and ${MAX_IMAGE_MB} MB or smaller.`);
      const {data,error}=await supabase.auth.signUp({email,password:pw,options:{data:{team_name:teamName,display_name:name,phone,requested_role:role}}});if(error)throw error;if(!data.user)throw new Error("Registration could not be created.");
      if(data.session&&file){try{const url=await uploadFile(LOGO_BUCKET,data.user.id,file);const {data:tm}=await supabase.from("teams").select("id").eq("name",teamName).maybeSingle();if(tm?.id)await supabase.rpc("update_team_profile",{p_team_id:tm.id,p_team_name:teamName,p_igl_name:role==="leader"?name:"",p_logo_url:url,p_member_name:name,p_phone:phone});}catch(x){console.warn("Optional logo save failed",x);}}
      await supabase.auth.signOut();state.screen="login";render();showToast("Registration successful. Your application is now PENDING for admin approval.");
    }catch(error){console.error(error);showToast(error.message||"Registration failed.","error");}}

  async function uploadFile(bucket,uid,file){const ext=file.name.split(".").pop().toLowerCase(),path=`${uid}/${crypto.randomUUID()}.${ext}`;const {error}=await supabase.storage.from(bucket).upload(path,file,{cacheControl:"3600",upsert:false,contentType:file.type});if(error)throw error;return supabase.storage.from(bucket).getPublicUrl(path).data.publicUrl;}

  /* ---------------- ADMIN LOGIN ---------------- */
  function renderAdminLogin(){app.innerHTML=`${authHeader(false)}<main class="public-page"><div class="auth-layout" style="grid-template-columns:.9fr 1.1fr;max-width:900px"><section class="card auth-hero" style="min-height:0"><div class="kicker">RESTRICTED CONTROL</div><h1>ADMIN <span style="color:var(--blue2)">CENTER</span></h1><h2>7TH UNIVERSE ESPORTS</h2><div class="desc">Review registrations, verify permanent match results, manage teams and moderate platform posts.</div><div class="access-note"><b>PRIVATE:</b> Only an approved administrator can enter.</div></section><section class="card auth-card"><div class="auth-inner"><div class="auth-logo-row"><img src="./7th-universe-esports-logo.png" alt="7U"><div><strong>ADMIN LOGIN</strong><span>CONTROL CENTER</span></div></div><form id="adminLoginForm"><div class="field-grid"><label class="full">ADMIN EMAIL / MOBILE<input id="adminId" required></label><label class="full">PASSWORD<input id="adminPw" type="password" required></label></div><div class="auth-actions"><button class="btn btn-primary" type="submit">LOGIN AS ADMIN</button><button class="btn btn-dark" type="button" id="adminBack">BACK</button></div></form></div></section></div></main>`;document.getElementById("publicRegisterBtn")?.addEventListener("click",goRegister);document.getElementById("adminLoginForm")?.addEventListener("submit",handleAdminLogin);document.getElementById("adminBack")?.addEventListener("click",goLogin);}
  async function handleAdminLogin(e){e.preventDefault();try{const id=document.getElementById("adminId").value.trim(),pw=document.getElementById("adminPw").value,creds=id.includes("@")?{email:id.toLowerCase(),password:pw}:{phone:cleanPhone(id),password:pw};const {data,error}=await supabase.auth.signInWithPassword(creds);if(error)throw error;const p=await getProfile(data.user.id);if(!p||p.role!=="admin"||p.status!=="approved"){await supabase.auth.signOut();throw new Error("This account does not have approved administrator access.");}state.user=data.user;state.profile=p;state.isAdmin=true;state.membership=await getMembership(data.user.id);state.team=state.membership?.teams||null;state.screen="member";state.section="admin";render();showToast("Administrator access granted.");}catch(error){console.error(error);showToast(error.message||"Admin login failed.","error");}}

  /* ---------------- MEMBER SHELL ---------------- */
  const navLink=(section,label)=>`<button class="app-link ${state.section===section?"active":""}" data-section="${section}">${label}</button>`;
  function memberHeader(){return `<div class="app-header"><div class="app-nav"><div class="app-brand"><img src="./7th-universe-esports-logo.png" alt="7U"><div><strong>7TH <span style="color:var(--blue2)">UNIVERSE</span></strong><span>FREE FIRE ESPORTS</span></div></div><nav class="app-nav-links">${navLink("dashboard","DASHBOARD")}${navLink("practice","PRACTICE")}${navLink("results","RESULTS")}${navLink("rankings","RANKINGS")}${navLink("recruitment","RECRUITMENT")}${navLink("my-posts","MY POSTS")}${navLink("team-profile","TEAM PROFILE")}${state.isAdmin?navLink("admin","ADMIN"):""}<button class="app-link" id="logoutBtn">LOGOUT</button></nav><div class="profile-chip">${logo(state.team?.logo_url,state.team?.name||"7U","profile-logo")}<div class="profile-meta"><small>${esc(roleName(state.profile?.role))}</small><strong>${esc(state.team?.name||state.profile?.display_name||"Member")}</strong></div></div></div></div>`;}
  function renderMember(){app.innerHTML=`${memberHeader()}<main id="memberRoot" class="page"></main>`;document.querySelectorAll("[data-section]").forEach(b=>b.addEventListener("click",()=>{state.section=b.dataset.section;renderMember();}));document.getElementById("logoutBtn")?.addEventListener("click",()=>supabase.auth.signOut());loadMemberSection();}
  async function loadMemberSection(){const root=document.getElementById("memberRoot");if(!root)return;try{if(state.section==="dashboard")root.innerHTML=await dashboardPage();else if(state.section==="practice"){root.innerHTML=await practicePage();bindPractice();}else if(state.section==="results"){root.innerHTML=await resultsPage();bindResults();}else if(state.section==="rankings")root.innerHTML=await rankingsPage();else if(state.section==="recruitment"){root.innerHTML=recruitmentPage();bindRecruitment();}else if(state.section==="my-posts")root.innerHTML=await myPostsPage();else if(state.section==="team-profile"){root.innerHTML=teamProfilePage();bindTeamProfile();}else if(state.section==="admin"&&state.isAdmin){root.innerHTML=await adminPage();bindAdmin();}else{state.section="dashboard";renderMember();return;}bindCards();}catch(error){console.error(error);root.innerHTML=`<div class="container"><div class="empty"><b style="color:#fff">${esc(error.message||"Section failed to load.")}</b></div></div>`;}}

  async function openChallenges(){const {data,error}=await supabase.from("practice_challenges").select("*").eq("status","open").order("match_time",{ascending:true}).limit(100);if(error)throw error;state.challenges=data||[];return state.challenges;}
  async function openRecruitment(){const {data,error}=await supabase.from("recruitment_posts").select("*").eq("status","open").order("created_at",{ascending:false}).limit(100);if(error)throw error;state.recruitment=data||[];return state.recruitment;}
  async function getRankings(){const {data,error}=await supabase.from("team_rankings").select("*").order("rank_number",{ascending:true}).limit(250);if(error)throw error;state.rankings=data||[];return state.rankings;}

  async function dashboardPage(){const [ch,re,rk]=await Promise.all([openChallenges(),openRecruitment(),getRankings()]);const mine=state.team?rk.find(x=>x.team_id===state.team.id):null;return `<div class="container"><section class="hero"><div class="kicker">7TH UNIVERSE ESPORTS • MEMBER HUB</div><h2>${esc(state.team?.name||state.profile?.display_name||"WELCOME")}</h2><p>Free Fire esports workspace for Clash Squad practice, permanent results, recruitment and all-time rankings.</p><div class="hero-actions"><button class="btn btn-primary" data-go="practice">⚔ CREATE PRACTICE</button><button class="btn btn-cyan" data-go="results">＋ SUBMIT RESULT</button><button class="btn btn-dark" data-go="rankings">★ VIEW RANKINGS</button><button class="btn btn-dark" data-go="team-profile">◈ TEAM PROFILE</button>${state.isAdmin?`<button class="btn btn-dark" data-go="admin">▣ ADMIN CENTER</button>`:""}</div></section><section class="quick-grid"><div class="quick"><div class="qicon">${mine?"#"+esc(mine.rank_number):"—"}</div><b>ALL-TIME RANK</b><span>Permanent position. Never reset.</span></div><div class="quick"><div class="qicon">${mine?esc(mine.total_points):0}</div><b>PERMANENT POINTS</b><span>WIN +3 • LOSS −3.</span></div><div class="quick"><div class="qicon">${mine?esc(mine.wins):0}</div><b>WINS</b><span>Verified permanent results.</span></div><div class="quick"><div class="qicon">${mine?esc(mine.losses):0}</div><b>LOSSES</b><span>Verified permanent results.</span></div></section><section class="member-grid"><div class="panel"><div class="panel-head"><div><div class="kicker">LIVE ARENA</div><h3>OPEN PRACTICE</h3></div><span class="badge badge-green">${ch.length} LIVE</span></div><div class="feed-list">${ch.slice(0,5).map(challengeCard).join("")||`<div class="empty">No open practice challenges.</div>`}</div></div><div class="stack"><div class="panel"><div class="panel-head"><div><div class="kicker">ALL-TIME</div><h3>TOP RANKING</h3></div><span class="badge badge-blue">NEVER RESET</span></div><div class="feed-list">${rk.slice(0,5).map(rankingMini).join("")||`<div class="empty">No active teams.</div>`}</div></div><div class="panel"><div class="panel-head"><div><div class="kicker">DIRECTORY</div><h3>RECRUITMENT</h3></div><span class="badge badge-cyan">${re.length} OPEN</span></div><div class="feed-list">${re.slice(0,4).map(recruitmentCard).join("")||`<div class="empty">No recruitment posts.</div>`}</div></div></div></section></div>`;}

  function challengeCard(c){return `<article class="challenge-card"><div class="row-between"><div class="identity">${logo(c.team_logo_url,c.team_name||"7U")}<div><div class="name">${esc(c.team_name)}</div><div class="meta">FREE FIRE • CLASH SQUAD • EVERYONE</div></div></div><span class="badge badge-green">OPEN</span></div><div class="pills"><span class="pill">${esc(c.match_type)}</span><span class="pill">${esc(c.format)}</span><span class="pill">EVERYONE</span></div><div class="info-row"><div class="info-box"><small>Match Time</small><strong>${esc(formatDate(c.match_time))}</strong></div><div class="info-box"><small>Contact</small><strong>${esc(c.contact||"—")}</strong></div></div>${c.notes?`<div class="note">${esc(c.notes)}</div>`:""}<div class="card-actions"><button class="btn btn-primary btn-small" data-wa="${esc(c.contact||"")}">CONTACT</button><button class="btn btn-dark btn-small" data-json='${esc(JSON.stringify(c))}'>DETAILS</button></div></article>`;}
  function recruitmentCard(r){const roles=Array.isArray(r.looking_for)?r.looking_for.join(" • "):(r.looking_for||"—");return `<article class="recruit-card"><div class="row-between"><div class="identity">${logo(r.team_logo_url,r.team_name||r.player_ign||"7U")}<div><div class="name">${esc(r.team_name||r.player_ign||"PLAYER")}</div><div class="meta">FREE FIRE • ${esc(String(r.listing_type||"").replaceAll("_"," "))}</div></div></div><span class="badge badge-cyan">OPEN</span></div><div class="pills"><span class="pill">${esc(roles)}</span>${r.players_needed?`<span class="pill">${esc(r.players_needed)} NEEDED</span>`:""}</div><div class="info-row"><div class="info-box"><small>Availability</small><strong>${esc(r.availability||"—")}</strong></div><div class="info-box"><small>Age</small><strong>${esc(r.age_requirement||"—")}</strong></div>${r.player_ign?`<div class="info-box"><small>IGN</small><strong>${esc(r.player_ign)}</strong></div>`:""}</div>${r.notes?`<div class="note">${esc(r.notes)}</div>`:""}<div class="card-actions"><button class="btn btn-cyan btn-small" data-wa="${esc(r.contact||"")}">CONTACT</button><button class="btn btn-dark btn-small" data-json='${esc(JSON.stringify(r))}'>DETAILS</button></div></article>`;}
  function rankingMini(r){return `<div class="challenge-card"><div class="row-between"><div class="identity">${logo(r.logo_url,r.team_name)}<div><div class="name">#${esc(r.rank_number)} ${esc(r.team_name)}</div><div class="meta">${esc(r.wins)} W • ${esc(r.losses)} L • ${esc(r.matches)} MATCHES</div></div></div><span class="badge badge-blue">${esc(r.total_points)} PTS</span></div></div>`;}

  /* ---------- Practice ---------- */
  async function practicePage(){const ch=await openChallenges();return `<div class="container"><div style="margin-bottom:16px"><div class="kicker">LIVE ARENA</div><h1 class="title">CLASH SQUAD PRACTICE</h1><div class="desc">Post an open challenge for <b>EVERYONE</b>. No specific opponent/team selector exists.</div></div><section class="panel form-card"><div class="panel-head"><div><div class="kicker">CREATE</div><h3>PRACTICE CHALLENGE</h3></div><span class="badge badge-blue">EVERYONE</span></div><div class="form-tip">FREE FIRE • CLASH SQUAD • EVERYONE • SINGLE / BEST OF 3 • SQUAD / TRIO / DUO / SOLO</div><form id="practiceForm"><div class="field-grid"><label>MATCH TYPE *<select id="practiceMatchType"><option value="SINGLE">SINGLE MATCH</option><option value="BEST OF 3">BEST OF 3</option></select></label><label>FORMAT *<select id="practiceFormat"><option value="SQUAD">SQUAD</option><option value="TRIO">TRIO</option><option value="DUO">DUO</option><option value="SOLO">SOLO</option></select></label><label>MATCH TIME *<input id="practiceTime" type="datetime-local" required></label><label>CONTACT / WHATSAPP *<input id="practiceContact" value="${esc(state.profile?.phone||"")}" required placeholder="03XXXXXXXXX"></label><label class="full">ADDITIONAL NOTES<textarea id="practiceNotes" maxlength="500"></textarea></label></div><div class="auth-actions" style="justify-content:flex-start"><button class="btn btn-primary" type="submit">POST OPEN CHALLENGE</button></div></form></section><section class="section"><div class="panel-head"><div><div class="kicker">PUBLIC LIST</div><h3>OPEN CHALLENGES</h3></div><span class="badge badge-green">${ch.length} LIVE</span></div><div class="feed-list">${ch.map(challengeCard).join("")||`<div class="empty">No open challenges.</div>`}</div></section></div>`;}
  function bindPractice(){document.getElementById("practiceForm")?.addEventListener("submit",submitPractice);}
  async function submitPractice(e){e.preventDefault();try{if(!state.team)throw new Error("Approved team membership is required.");const dt=new Date(document.getElementById("practiceTime").value);if(Number.isNaN(dt.getTime()))throw new Error("Choose a valid match time.");const contact=cleanPhone(document.getElementById("practiceContact").value);if(!/^\+92\d{10}$/.test(contact))throw new Error("Enter a valid Pakistan contact number.");const {data,error}=await supabase.rpc("create_practice_challenge",{p_team_id:state.team.id,p_team_name:state.team.name,p_team_logo_url:state.team.logo_url||null,p_match_type:document.getElementById("practiceMatchType").value,p_match_time:dt.toISOString(),p_format:document.getElementById("practiceFormat").value,p_contact:contact,p_notes:document.getElementById("practiceNotes").value.trim()||null});if(error)throw error;showToast("Practice challenge posted for EVERYONE.");await loadMemberSection();bindCards();}catch(err){console.error(err);showToast(err.message||"Could not post challenge.","error");}}

  /* ---------- Results ---------- */
  async function getMyResults(){const {data,error}=await supabase.from("team_match_results").select("*").eq("team_id",state.team?.id||"00000000-0000-0000-0000-000000000000").order("played_at",{ascending:false}).limit(100);if(error)throw error;return data||[];}
  async function getVerifiedResults(){const {data,error}=await supabase.from("team_match_results").select("*").eq("status","approved").order("played_at",{ascending:false}).limit(100);if(error)throw error;return data||[];}
  function resultCard(r){const win=r.outcome==="WIN";return `<div class="challenge-card"><div class="row-between"><div><div class="name">VS ${esc(r.opponent_team_name)}</div><div class="meta">${esc(r.match_type)} • ${esc(r.format)} • ${esc(formatDate(r.played_at))}</div></div><span class="badge ${win?"badge-green":"badge-danger"}">${win?"WIN +3":"LOSS −3"}</span></div><div class="pills"><span class="pill">${esc(String(r.status||"pending").toUpperCase())}</span>${r.opponent_team_uid?`<span class="pill">UID ${esc(r.opponent_team_uid)}</span>`:""}</div>${r.notes?`<div class="note">${esc(r.notes)}</div>`:""}${r.proof_url?`<div class="card-actions"><button class="btn btn-dark btn-small" data-proof="${esc(r.proof_url)}">VIEW PROOF</button></div>`:""}</div>`;}
  async function resultsPage(){const [mine,verified]=await Promise.all([getMyResults(),getVerifiedResults()]);return `<div class="container"><div style="margin-bottom:16px"><div class="kicker">PERMANENT RECORD</div><h1 class="title">MATCH RESULTS</h1><div class="desc">Submit completed matches. <b>WIN = +3</b> • <b>LOSS = −3</b>. Results remain part of the permanent all-time record after approval.</div></div><section class="panel form-card"><div class="panel-head"><div><div class="kicker">SUBMIT FOR REVIEW</div><h3>TEAM RESULT</h3></div><span class="badge badge-blue">ALL-TIME</span></div><form id="resultForm"><div class="field-grid"><label>OPPONENT TEAM NAME *<input id="resultOpponent" maxlength="80" required></label><label>RESULT *<select id="resultOutcome"><option value="WIN">WIN • +3 POINTS</option><option value="LOSS">LOSS • −3 POINTS</option></select></label><label>MATCH TYPE *<select id="resultMatchType"><option value="SINGLE">SINGLE MATCH</option><option value="BEST OF 3">BEST OF 3</option></select></label><label>FORMAT *<select id="resultFormat"><option value="SQUAD">SQUAD</option><option value="TRIO">TRIO</option><option value="DUO">DUO</option><option value="SOLO">SOLO</option></select></label><label>MATCH DATE / TIME *<input id="resultPlayedAt" type="datetime-local" required></label><label>OPPONENT UID<small style="font-size:7px;color:#587189">optional</small><input id="resultOpponentUid" maxlength="30"></label><label class="full">PROOF SCREENSHOT — OPTIONAL<input id="resultProof" type="file" accept="image/png,image/jpeg,image/webp"><div class="hint">PNG/JPG/WEBP • Maximum ${MAX_IMAGE_MB} MB.</div></label><label class="full">NOTES<textarea id="resultNotes" maxlength="600"></textarea></label></div><div class="access-note"><b>SCORING:</b> WIN +3 • LOSS −3 • NO WEEKLY RESET • NO SEASON RESET</div><div class="auth-actions" style="justify-content:flex-start"><button class="btn btn-cyan" type="submit">SUBMIT RESULT</button></div></form></section><section class="section"><div class="member-grid"><div class="panel"><div class="panel-head"><div><div class="kicker">YOUR TEAM</div><h3>MY RESULTS</h3></div></div><div class="feed-list">${mine.map(resultCard).join("")||`<div class="empty">No results submitted yet.</div>`}</div></div><div class="panel"><div class="panel-head"><div><div class="kicker">VERIFIED</div><h3>RECENT RESULTS</h3></div></div><div class="feed-list">${verified.slice(0,15).map(resultCard).join("")||`<div class="empty">No approved results yet.</div>`}</div></div></div></section></div>`;}
  function bindResults(){document.getElementById("resultForm")?.addEventListener("submit",submitResult);document.querySelectorAll("[data-proof]").forEach(b=>b.addEventListener("click",()=>showModal("RESULT PROOF",`<img src="${esc(b.dataset.proof)}" style="width:100%;border-radius:12px;border:1px solid #214460">`)));}
  async function submitResult(e){e.preventDefault();try{if(!state.team)throw new Error("Approved team membership is required.");const file=document.getElementById("resultProof").files?.[0]||null;if(file&&(file.size>MAX_IMAGE_MB*1024*1024||!/^image\/(png|jpeg|webp)$/.test(file.type)))throw new Error(`Proof image must be PNG/JPG/WEBP and ${MAX_IMAGE_MB} MB or smaller.`);const dt=new Date(document.getElementById("resultPlayedAt").value);if(Number.isNaN(dt.getTime()))throw new Error("Choose a valid match date/time.");let proof=null;if(file)proof=await uploadFile(RESULT_BUCKET,state.user.id,file);const {error}=await supabase.rpc("submit_team_result",{p_team_id:state.team.id,p_opponent_team_name:document.getElementById("resultOpponent").value.trim(),p_opponent_team_uid:document.getElementById("resultOpponentUid").value.trim()||null,p_match_type:document.getElementById("resultMatchType").value,p_format:document.getElementById("resultFormat").value,p_outcome:document.getElementById("resultOutcome").value,p_played_at:dt.toISOString(),p_proof_url:proof,p_notes:document.getElementById("resultNotes").value.trim()||null});if(error)throw error;showToast("Result submitted for admin review. It will count after approval.");await loadMemberSection();bindCards();}catch(err){console.error(err);showToast(err.message||"Could not submit result.","error");}}

  /* ---------- Rankings ---------- */
  async function rankingsPage(){const rk=await getRankings();return `<div class="container"><div style="margin-bottom:16px"><div class="kicker">PERMANENT LEADERBOARD</div><h1 class="title">ALL-TIME RANKINGS</h1><div class="desc"><b>NEVER RESET.</b> Only administrator-approved match results affect permanent points.</div></div><section class="panel"><div class="panel-head"><div><div class="kicker">FREE FIRE ESPORTS</div><h3>TEAM RANKING</h3></div><span class="badge badge-blue">PERMANENT</span></div><div class="table-shell"><table><thead><tr><th>#</th><th>Team</th><th>Points</th><th>Matches</th><th>Wins</th><th>Losses</th><th>Win Rate</th></tr></thead><tbody>${rk.map(r=>`<tr ${state.team?.id===r.team_id?'style="background:rgba(14,108,255,.05)"':''}><td><strong>#${esc(r.rank_number)}</strong></td><td><div class="identity">${logo(r.logo_url,r.team_name,"mini-logo")}<div><strong>${esc(r.team_name)}</strong><div style="color:#5a738b;margin-top:2px">IGL: ${esc(r.igl_name||"—")}</div></div></div></td><td><span class="badge badge-blue">${esc(r.total_points)}</span></td><td>${esc(r.matches)}</td><td>${esc(r.wins)}</td><td>${esc(r.losses)}</td><td>${esc(r.win_rate)}%</td></tr>`).join("")||`<tr><td colspan="7">No active teams yet.</td></tr>`}</tbody></table></div></section></div>`;}

  /* ---------- Recruitment ---------- */
  function recruitmentPage(){return `<div class="container"><div style="margin-bottom:16px"><div class="kicker">COMPETITIVE DIRECTORY</div><h1 class="title">FREE FIRE RECRUITMENT</h1><div class="desc">Create a team requirement or publish a player profile.</div></div><section class="panel form-card"><div class="panel-head"><div><div class="kicker">CREATE</div><h3>RECRUITMENT POST</h3></div><span class="badge badge-cyan">TEAM + PLAYER</span></div><form id="recruitForm"><label style="margin-bottom:12px">LISTING TYPE *<select id="recruitType"><option value="TEAM_RECRUITMENT">TEAM RECRUITMENT — WE NEED PLAYERS</option><option value="PLAYER_RECRUITMENT">PLAYER RECRUITMENT — I NEED A TEAM</option></select></label><div id="teamFields"><div class="field-grid"><label>TEAM NAME<input value="${esc(state.team?.name||"")}" disabled></label><label>PLAYERS NEEDED<select id="recruitPlayersNeeded"><option>1</option><option>2</option><option>3</option><option>4</option></select></label><label class="full">LOOKING FOR *<select id="recruitLookingFor" multiple size="5"><option>Rusher</option><option>Sniper</option><option>Support</option><option>Entry Fragger</option><option>All-Rounder</option></select></label></div></div><div id="playerFields" class="hidden"><div class="field-grid"><label>PLAYER IGN *<input id="playerIgn" maxlength="40"></label><label>FREE FIRE UID *<input id="playerUid" maxlength="20"></label><label class="full">PREFERRED ROLE *<select id="playerRole"><option>Rusher</option><option>Sniper</option><option>Support</option><option>Entry Fragger</option><option>All-Rounder</option></select></label></div></div><div class="field-grid" style="margin-top:12px"><label>AVAILABILITY *<input id="recruitAvailability" required placeholder="5 PM – 11 PM"></label><label>AGE / AGE REQUIREMENT *<input id="recruitAge" required placeholder="16+"></label><label>CONTACT / WHATSAPP *<input id="recruitContact" value="${esc(state.profile?.phone||"")}" required></label><label>EXPERIENCE<input id="recruitExperience" maxlength="160"></label><label class="full">EXTRA DETAILS<textarea id="recruitNotes" maxlength="600"></textarea></label></div><div class="auth-actions" style="justify-content:flex-start"><button class="btn btn-cyan" type="submit">PUBLISH RECRUITMENT</button></div></form></section></div>`;}
  function bindRecruitment(){document.getElementById("recruitType")?.addEventListener("change",toggleRecruit);document.getElementById("recruitForm")?.addEventListener("submit",submitRecruit);toggleRecruit();}
  function toggleRecruit(){const team=document.getElementById("recruitType")?.value==="TEAM_RECRUITMENT";document.getElementById("teamFields")?.classList.toggle("hidden",!team);document.getElementById("playerFields")?.classList.toggle("hidden",team);if(document.getElementById("playerIgn"))document.getElementById("playerIgn").required=!team;if(document.getElementById("playerUid"))document.getElementById("playerUid").required=!team;}
  async function submitRecruit(e){e.preventDefault();try{const type=document.getElementById("recruitType").value,contact=cleanPhone(document.getElementById("recruitContact").value);if(!/^\+92\d{10}$/.test(contact))throw new Error("Enter a valid Pakistan contact number.");let roles=[],ign=null,uid=null;if(type==="TEAM_RECRUITMENT"){if(!state.team)throw new Error("Approved team membership is required.");roles=[...document.getElementById("recruitLookingFor").selectedOptions].map(o=>o.value);if(!roles.length)throw new Error("Select at least one role.");}else{ign=document.getElementById("playerIgn").value.trim();uid=document.getElementById("playerUid").value.trim();roles=[document.getElementById("playerRole").value];if(!ign||!uid)throw new Error("Player IGN and UID are required.");}const {error}=await supabase.rpc("create_recruitment_post",{p_team_id:state.team?.id||null,p_team_name:state.team?.name||ign,p_team_logo_url:state.team?.logo_url||null,p_listing_type:type,p_looking_for:roles,p_players_needed:type==="TEAM_RECRUITMENT"?Number(document.getElementById("recruitPlayersNeeded").value):1,p_availability:document.getElementById("recruitAvailability").value.trim(),p_age_requirement:document.getElementById("recruitAge").value.trim(),p_contact:contact,p_experience:document.getElementById("recruitExperience").value.trim()||null,p_player_ign:ign,p_player_uid:uid,p_notes:document.getElementById("recruitNotes").value.trim()||null});if(error)throw error;showToast("Recruitment post published.");await loadMemberSection();bindCards();}catch(err){console.error(err);showToast(err.message||"Could not publish recruitment.","error");}}

  /* ---------- Team Profile ---------- */
  function teamProfilePage(){if(!state.team)return `<div class="container"><div class="empty">No approved team is attached to this account.</div></div>`;const leader=state.profile?.role==="leader";return `<div class="container"><div style="margin-bottom:16px"><div class="kicker">TEAM IDENTITY</div><h1 class="title">TEAM PROFILE</h1><div class="desc">Update the team logo, team name and IGL name. Changes synchronize to existing practice/recruitment cards.</div></div><section class="member-grid"><div class="panel"><div class="panel-head"><div><div class="kicker">CURRENT</div><h3>${esc(state.team.name)}</h3></div><span class="badge badge-green">${esc(state.team.status)}</span></div><div style="display:flex;align-items:center;gap:14px">${logo(state.team.logo_url,state.team.name,"profile-logo")}<div><div class="name">${esc(state.team.name)}</div><div class="meta">IGL: ${esc(state.team.igl_name||"—")}</div></div></div></div><div class="panel"><div class="panel-head"><div><div class="kicker">EDIT</div><h3>TEAM SETTINGS</h3></div></div><form id="teamProfileForm"><div class="field-grid"><label>TEAM NAME *<input id="profileTeamName" value="${esc(state.team.name)}" maxlength="50" required></label><label>IGL NAME *<input id="profileIglName" value="${esc(state.team.igl_name||"")}" maxlength="60" ${leader||state.isAdmin?"":"disabled"} required></label><label>MY MEMBER NAME<input id="profileMemberName" value="${esc(state.profile?.display_name||"")}" maxlength="60"></label><label>MY CONTACT<input id="profilePhone" value="${esc(state.profile?.phone||"")}" maxlength="20"></label><label class="full">NEW TEAM LOGO — OPTIONAL<input id="profileLogo" type="file" accept="image/png,image/jpeg,image/webp"><div class="hint">Leave empty to keep current logo.</div></label></div><div class="auth-actions" style="justify-content:flex-start"><button class="btn btn-primary" type="submit">SAVE TEAM PROFILE</button></div></form></div></section></div>`;}
  function bindTeamProfile(){document.getElementById("teamProfileForm")?.addEventListener("submit",saveTeamProfile);}
  async function saveTeamProfile(e){e.preventDefault();try{const teamName=document.getElementById("profileTeamName").value.trim(),igl=document.getElementById("profileIglName").value.trim(),memberName=document.getElementById("profileMemberName").value.trim(),phone=cleanPhone(document.getElementById("profilePhone").value),file=document.getElementById("profileLogo").files?.[0]||null;if(!teamName||!igl)throw new Error("Team name and IGL name are required.");if(phone&&!/^\+92\d{10}$/.test(phone))throw new Error("Enter a valid Pakistan contact number.");let url=state.team.logo_url||null;if(file){if(file.size>MAX_IMAGE_MB*1024*1024||!/^image\/(png|jpeg|webp)$/.test(file.type))throw new Error(`Logo must be PNG/JPG/WEBP and ${MAX_IMAGE_MB} MB or smaller.`);url=await uploadFile(LOGO_BUCKET,state.user.id,file);}const {error}=await supabase.rpc("update_team_profile",{p_team_id:state.team.id,p_team_name:teamName,p_igl_name:igl,p_logo_url:url,p_member_name:memberName||state.profile.display_name,p_phone:phone||state.profile.phone||null});if(error)throw error;state.profile=await getProfile(state.user.id);state.membership=await getMembership(state.user.id);state.team=state.membership?.teams||state.team;showToast("Team profile updated successfully.");renderMember();}catch(err){console.error(err);showToast(err.message||"Could not update team profile.","error");}}

  /* ---------- My Posts ---------- */
  async function myPostsPage(){if(!state.team)return `<div class="container"><div class="empty">No team attached.</div></div>`;const [c,r]=await Promise.all([supabase.from("practice_challenges").select("*").eq("team_id",state.team.id).order("created_at",{ascending:false}),supabase.from("recruitment_posts").select("*").eq("team_id",state.team.id).order("created_at",{ascending:false})]);if(c.error)throw c.error;if(r.error)throw r.error;return `<div class="container"><div style="margin-bottom:16px"><div class="kicker">TEAM ACTIVITY</div><h1 class="title">MY POSTS</h1><div class="desc">${esc(state.team.name)}</div></div><section class="member-grid"><div class="panel"><div class="panel-head"><div><div class="kicker">Practice</div><h3>MY CHALLENGES</h3></div></div><div class="feed-list">${(c.data||[]).map(challengeCard).join("")||`<div class="empty">No practice posts.</div>`}</div></div><div class="panel"><div class="panel-head"><div><div class="kicker">Recruitment</div><h3>MY RECRUITMENT</h3></div></div><div class="feed-list">${(r.data||[]).map(recruitmentCard).join("")||`<div class="empty">No recruitment posts.</div>`}</div></div></section></div>`;}

  /* ---------- Admin ---------- */
  async function adminPage(){const [p,t,c,r,res]=await Promise.all([supabase.from("profiles").select("*").neq("role","admin").order("created_at",{ascending:false}).limit(300),supabase.from("teams").select("*").order("created_at",{ascending:false}).limit(300),supabase.from("practice_challenges").select("*").order("created_at",{ascending:false}).limit(300),supabase.from("recruitment_posts").select("*").order("created_at",{ascending:false}).limit(300),supabase.from("team_match_results").select("*").order("created_at",{ascending:false}).limit(300)]);for(const q of [p,t,c,r,res])if(q.error)throw q.error;state.registrations=p.data||[];state.teams=t.data||[];state.challenges=c.data||[];state.recruitment=r.data||[];state.results=res.data||[];const pending=state.registrations.filter(x=>x.status==="pending").length,resultPending=state.results.filter(x=>x.status==="pending").length;return `<div class="container"><div style="margin-bottom:16px"><div class="kicker">RESTRICTED CONTROL</div><h1 class="title">ADMIN CONTROL CENTER</h1><div class="desc">Approval, verification, moderation and team controls.</div></div><div class="quick-grid"><div class="quick"><div class="qicon">${pending}</div><b>PENDING MEMBERS</b><span>Registration queue.</span></div><div class="quick"><div class="qicon">${resultPending}</div><b>PENDING RESULTS</b><span>Verification queue.</span></div><div class="quick"><div class="qicon">${state.teams.length}</div><b>TEAMS</b><span>Registered teams.</span></div><div class="quick"><div class="qicon">${state.results.filter(x=>x.status==="approved").length}</div><b>VERIFIED RESULTS</b><span>Permanent records.</span></div></div><div class="admin-grid" style="margin-top:16px"><aside class="admin-tabs"><button class="admin-tab ${state.adminSection==="registrations"?"active":""}" data-admin="registrations">REGISTRATIONS <span class="admin-count">${pending}</span></button><button class="admin-tab ${state.adminSection==="results"?"active":""}" data-admin="results">RESULTS <span class="admin-count">${resultPending}</span></button><button class="admin-tab ${state.adminSection==="teams"?"active":""}" data-admin="teams">TEAMS</button><button class="admin-tab ${state.adminSection==="practice"?"active":""}" data-admin="practice">PRACTICE</button><button class="admin-tab ${state.adminSection==="recruitment"?"active":""}" data-admin="recruitment">RECRUITMENT</button></aside><section>${adminContent()}</section></div></div>`;}
  function adminContent(){
    if(state.adminSection==="results")return `<div class="panel"><div class="panel-head"><div><div class="kicker">VERIFY</div><h3>MATCH RESULTS</h3><div class="subtle">Only approved results affect the permanent ranking.</div></div></div><div class="table-shell"><table><thead><tr><th>Team</th><th>Opponent</th><th>Outcome</th><th>Points</th><th>Played</th><th>Status</th><th>Control</th></tr></thead><tbody>${state.results.map(r=>`<tr><td>${esc(r.team_id)}</td><td>${esc(r.opponent_team_name)}</td><td>${esc(r.outcome)}</td><td>${r.outcome==="WIN"?"+3":"−3"}</td><td>${esc(formatDate(r.played_at))}</td><td>${esc(r.status)}</td><td>${r.status==="pending"?`<button class="btn btn-green btn-small" data-review="${esc(r.id)}" data-next="approved">APPROVE</button> <button class="btn btn-danger btn-small" data-review="${esc(r.id)}" data-next="rejected">REJECT</button>`:"—"}</td></tr>`).join("")||`<tr><td colspan="7">No results.</td></tr>`}</tbody></table></div></div>`;
    if(state.adminSection==="teams")return `<div class="panel"><div class="panel-head"><div><div class="kicker">DIRECTORY</div><h3>ALL TEAMS</h3></div></div><div class="table-shell"><table><thead><tr><th>Team</th><th>IGL</th><th>Status</th><th>Created</th><th>Control</th></tr></thead><tbody>${state.teams.map(t=>`<tr><td><div class="identity">${logo(t.logo_url,t.name)}<strong>${esc(t.name)}</strong></div></td><td>${esc(t.igl_name||"—")}</td><td>${esc(t.status)}</td><td>${esc(formatDate(t.created_at))}</td><td><button class="btn btn-dark btn-small" data-team-status="${esc(t.id)}" data-next="${t.status==="banned"?"active":"banned"}">${t.status==="banned"?"UNBAN":"BAN"}</button></td></tr>`).join("")||`<tr><td colspan="5">No teams.</td></tr>`}</tbody></table></div></div>`;
    if(state.adminSection==="practice")return `<div class="panel"><div class="panel-head"><div><div class="kicker">LIVE ARENA</div><h3>PRACTICE CHALLENGES</h3></div></div><div class="table-shell"><table><thead><tr><th>Team</th><th>Match</th><th>Format</th><th>Time</th><th>Status</th><th>Control</th></tr></thead><tbody>${state.challenges.map(c=>`<tr><td>${esc(c.team_name)}</td><td>${esc(c.match_type)}</td><td>${esc(c.format)}</td><td>${esc(formatDate(c.match_time))}</td><td>${esc(c.status)}</td><td><button class="btn btn-dark btn-small" data-post="practice" data-id="${esc(c.id)}" data-next="${c.status==="open"?"closed":"open"}">${c.status==="open"?"CLOSE":"REOPEN"}</button></td></tr>`).join("")||`<tr><td colspan="6">No challenges.</td></tr>`}</tbody></table></div></div>`;
    if(state.adminSection==="recruitment")return `<div class="panel"><div class="panel-head"><div><div class="kicker">DIRECTORY</div><h3>RECRUITMENT POSTS</h3></div></div><div class="table-shell"><table><thead><tr><th>Listing</th><th>Type</th><th>Roles</th><th>Availability</th><th>Status</th><th>Control</th></tr></thead><tbody>${state.recruitment.map(r=>`<tr><td>${esc(r.team_name||r.player_ign||"—")}</td><td>${esc(r.listing_type)}</td><td>${esc(Array.isArray(r.looking_for)?r.looking_for.join(", "):r.looking_for||"—")}</td><td>${esc(r.availability||"—")}</td><td>${esc(r.status)}</td><td><button class="btn btn-dark btn-small" data-post="recruitment" data-id="${esc(r.id)}" data-next="${r.status==="open"?"closed":"open"}">${r.status==="open"?"CLOSE":"REOPEN"}</button></td></tr>`).join("")||`<tr><td colspan="6">No recruitment.</td></tr>`}</tbody></table></div></div>`;
    const pending=state.registrations.filter(p=>p.status==="pending");return `<div class="panel"><div class="panel-head"><div><div class="kicker">FIRST PRIORITY</div><h3>PENDING REGISTRATIONS</h3><div class="subtle">New Auth signups appear here immediately.</div></div><span class="badge badge-warn">${pending.length} PENDING</span></div><div class="table-shell"><table><thead><tr><th>Member</th><th>Team</th><th>Role</th><th>Contact</th><th>Status</th><th>Control</th></tr></thead><tbody>${pending.map(p=>`<tr><td>${esc(p.display_name)}</td><td>${esc(p.team_name||"—")}</td><td>${esc(roleName(p.role))}</td><td>${esc(p.phone||"—")}</td><td>PENDING</td><td><button class="btn btn-green btn-small" data-profile="${esc(p.id)}" data-next="approved">APPROVE</button> <button class="btn btn-danger btn-small" data-profile="${esc(p.id)}" data-next="rejected">REJECT</button></td></tr>`).join("")||`<tr><td colspan="6"><div class="empty">No pending registrations.</div></td></tr>`}</tbody></table></div><div class="divider"></div><div class="panel-head"><div><div class="kicker">MEMBER DIRECTORY</div><h3>ALL MEMBERS</h3></div></div><div class="table-shell"><table><thead><tr><th>Member</th><th>Team</th><th>Role</th><th>Status</th><th>Control</th></tr></thead><tbody>${state.registrations.map(p=>`<tr><td>${esc(p.display_name)}</td><td>${esc(p.team_name||"—")}</td><td>${esc(roleName(p.role))}</td><td>${esc(p.status)}</td><td>${p.status==="approved"?`<button class="btn btn-dark btn-small" data-profile="${esc(p.id)}" data-next="banned">BAN</button>`:p.status==="banned"?`<button class="btn btn-dark btn-small" data-profile="${esc(p.id)}" data-next="approved">UNBAN</button>`:"—"}</td></tr>`).join("")||`<tr><td colspan="5">No members.</td></tr>`}</tbody></table></div></div>`;
  }
  function bindAdmin(){document.querySelectorAll("[data-admin]").forEach(b=>b.addEventListener("click",()=>{state.adminSection=b.dataset.admin;renderMember();}));document.querySelectorAll("[data-profile]").forEach(b=>b.addEventListener("click",()=>adminMember(b.dataset.profile,b.dataset.next)));document.querySelectorAll("[data-team-status]").forEach(b=>b.addEventListener("click",()=>adminTeam(b.dataset.teamStatus,b.dataset.next)));document.querySelectorAll("[data-review]").forEach(b=>b.addEventListener("click",()=>reviewResult(b.dataset.review,b.dataset.next)));document.querySelectorAll("[data-post]").forEach(b=>b.addEventListener("click",()=>adminPost(b.dataset.post,b.dataset.id,b.dataset.next)));}
  async function adminMember(uid,status){try{const {error}=await supabase.rpc("admin_set_member_status",{p_user_id:uid,p_status:status});if(error)throw error;showToast(`Member ${status}.`);renderMember();}catch(e){console.error(e);showToast(e.message||"Could not update member.","error");}}
  async function adminTeam(id,status){try{const {error}=await supabase.rpc("admin_set_team_status",{p_team_id:id,p_status:status});if(error)throw error;showToast(`Team ${status}.`);renderMember();}catch(e){console.error(e);showToast(e.message||"Could not update team.","error");}}
  async function reviewResult(id,status){try{const {error}=await supabase.rpc("admin_review_result",{p_result_id:id,p_status:status});if(error)throw error;showToast(`Result ${status}.`);renderMember();}catch(e){console.error(e);showToast(e.message||"Could not review result.","error");}}
  async function adminPost(kind,id,status){try{const fn=kind==="practice"?"admin_set_practice_status":"admin_set_recruitment_status";const {error}=await supabase.rpc(fn,{p_id:id,p_status:status});if(error)throw error;showToast(`Post ${status}.`);renderMember();}catch(e){console.error(e);showToast(e.message||"Could not update post.","error");}}

  function bindCards(){document.querySelectorAll("[data-go]").forEach(b=>b.addEventListener("click",()=>{state.section=b.dataset.go;renderMember();}));document.querySelectorAll("[data-wa]").forEach(b=>b.addEventListener("click",()=>{const p=cleanPhone(b.dataset.wa);if(!p)return showToast("No contact number available.","error");window.open(`https://wa.me/${p.replace("+","")}`,"_blank","noopener");}));document.querySelectorAll("[data-json]").forEach(b=>b.addEventListener("click",()=>{const item=JSON.parse(b.dataset.json);const body=Object.entries(item).filter(([k,v])=>!['id','team_id','team_logo_url','created_by'].includes(k)&&v!==null&&v!=="").map(([k,v])=>`<div class="info-box" style="margin-bottom:7px"><small>${esc(k.replaceAll("_"," "))}</small><strong>${esc(Array.isArray(v)?v.join(" • "):String(v))}</strong></div>`).join("");showModal("POST DETAILS",body||`<div class="empty">No additional details.</div>`);}));}

  function render(){if(state.screen==="admin-login")renderAdminLogin();else if(state.screen==="member")renderMember();else renderAuth();}
  hydrateSession().catch(e=>{console.error(e);render();showToast("Website loaded. Please log in.","error");});
})();
